// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BanpoFri.Data
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PlayerData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static PlayerData GetRootAsPlayerData(ByteBuffer _bb) { return GetRootAsPlayerData(_bb, new PlayerData()); }
  public static PlayerData GetRootAsPlayerData(ByteBuffer _bb, PlayerData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PlayerData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Hpcount { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)1; } }
  public bool MutateHpcount(int hpcount) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, hpcount); return true; } else { return false; } }

  public static Offset<BanpoFri.Data.PlayerData> CreatePlayerData(FlatBufferBuilder builder,
      int hpcount = 1) {
    builder.StartTable(1);
    PlayerData.AddHpcount(builder, hpcount);
    return PlayerData.EndPlayerData(builder);
  }

  public static void StartPlayerData(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddHpcount(FlatBufferBuilder builder, int hpcount) { builder.AddInt(0, hpcount, 1); }
  public static Offset<BanpoFri.Data.PlayerData> EndPlayerData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BanpoFri.Data.PlayerData>(o);
  }
  public PlayerDataT UnPack() {
    var _o = new PlayerDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(PlayerDataT _o) {
    _o.Hpcount = this.Hpcount;
  }
  public static Offset<BanpoFri.Data.PlayerData> Pack(FlatBufferBuilder builder, PlayerDataT _o) {
    if (_o == null) return default(Offset<BanpoFri.Data.PlayerData>);
    return CreatePlayerData(
      builder,
      _o.Hpcount);
  }
}

public class PlayerDataT
{
  [Newtonsoft.Json.JsonProperty("hpcount")]
  public int Hpcount { get; set; }

  public PlayerDataT() {
    this.Hpcount = 1;
  }
}


static public class PlayerDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Hpcount*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
