// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BanpoFri.Data
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct RecordCount : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static RecordCount GetRootAsRecordCount(ByteBuffer _bb) { return GetRootAsRecordCount(_bb, new RecordCount()); }
  public static RecordCount GetRootAsRecordCount(ByteBuffer _bb, RecordCount obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RecordCount __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Idx { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIdxBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetIdxBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetIdxArray() { return __p.__vector_as_array<byte>(4); }
  public int Count { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateCount(int count) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, count); return true; } else { return false; } }

  public static Offset<BanpoFri.Data.RecordCount> CreateRecordCount(FlatBufferBuilder builder,
      StringOffset idxOffset = default(StringOffset),
      int count = 0) {
    builder.StartTable(2);
    RecordCount.AddCount(builder, count);
    RecordCount.AddIdx(builder, idxOffset);
    return RecordCount.EndRecordCount(builder);
  }

  public static void StartRecordCount(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddIdx(FlatBufferBuilder builder, StringOffset idxOffset) { builder.AddOffset(0, idxOffset.Value, 0); }
  public static void AddCount(FlatBufferBuilder builder, int count) { builder.AddInt(1, count, 0); }
  public static Offset<BanpoFri.Data.RecordCount> EndRecordCount(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BanpoFri.Data.RecordCount>(o);
  }
  public RecordCountT UnPack() {
    var _o = new RecordCountT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(RecordCountT _o) {
    _o.Idx = this.Idx;
    _o.Count = this.Count;
  }
  public static Offset<BanpoFri.Data.RecordCount> Pack(FlatBufferBuilder builder, RecordCountT _o) {
    if (_o == null) return default(Offset<BanpoFri.Data.RecordCount>);
    var _idx = _o.Idx == null ? default(StringOffset) : builder.CreateString(_o.Idx);
    return CreateRecordCount(
      builder,
      _idx,
      _o.Count);
  }
}

public class RecordCountT
{
  [Newtonsoft.Json.JsonProperty("idx")]
  public string Idx { get; set; }
  [Newtonsoft.Json.JsonProperty("count")]
  public int Count { get; set; }

  public RecordCountT() {
    this.Idx = null;
    this.Count = 0;
  }
}


static public class RecordCountVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Idx*/, false)
      && verifier.VerifyField(tablePos, 6 /*Count*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
