// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BanpoFri.Data
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct StageData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static StageData GetRootAsStageData(ByteBuffer _bb) { return GetRootAsStageData(_bb, new StageData()); }
  public static StageData GetRootAsStageData(ByteBuffer _bb, StageData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public StageData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Stageidx { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)1; } }
  public bool MutateStageidx(int stageidx) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, stageidx); return true; } else { return false; } }
  public int Waveidx { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)1; } }
  public bool MutateWaveidx(int waveidx) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, waveidx); return true; } else { return false; } }
  public int Enemycount { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)1; } }
  public bool MutateEnemycount(int enemycount) { int o = __p.__offset(8); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, enemycount); return true; } else { return false; } }

  public static Offset<BanpoFri.Data.StageData> CreateStageData(FlatBufferBuilder builder,
      int stageidx = 1,
      int waveidx = 1,
      int enemycount = 1) {
    builder.StartTable(3);
    StageData.AddEnemycount(builder, enemycount);
    StageData.AddWaveidx(builder, waveidx);
    StageData.AddStageidx(builder, stageidx);
    return StageData.EndStageData(builder);
  }

  public static void StartStageData(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddStageidx(FlatBufferBuilder builder, int stageidx) { builder.AddInt(0, stageidx, 1); }
  public static void AddWaveidx(FlatBufferBuilder builder, int waveidx) { builder.AddInt(1, waveidx, 1); }
  public static void AddEnemycount(FlatBufferBuilder builder, int enemycount) { builder.AddInt(2, enemycount, 1); }
  public static Offset<BanpoFri.Data.StageData> EndStageData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BanpoFri.Data.StageData>(o);
  }
  public StageDataT UnPack() {
    var _o = new StageDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(StageDataT _o) {
    _o.Stageidx = this.Stageidx;
    _o.Waveidx = this.Waveidx;
    _o.Enemycount = this.Enemycount;
  }
  public static Offset<BanpoFri.Data.StageData> Pack(FlatBufferBuilder builder, StageDataT _o) {
    if (_o == null) return default(Offset<BanpoFri.Data.StageData>);
    return CreateStageData(
      builder,
      _o.Stageidx,
      _o.Waveidx,
      _o.Enemycount);
  }
}

public class StageDataT
{
  [Newtonsoft.Json.JsonProperty("stageidx")]
  public int Stageidx { get; set; }
  [Newtonsoft.Json.JsonProperty("waveidx")]
  public int Waveidx { get; set; }
  [Newtonsoft.Json.JsonProperty("enemycount")]
  public int Enemycount { get; set; }

  public StageDataT() {
    this.Stageidx = 1;
    this.Waveidx = 1;
    this.Enemycount = 1;
  }
}


static public class StageDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Stageidx*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Waveidx*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Enemycount*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
